WIP wait for layer file uploads to finish before deleting layer files
Test fails because of panic due to task::block_on() inside runtime thread.
I tried converting the call stack into async fn's to avoid use of
task::block_on(), but that doesn't work because layer_removal_cs is held
across await points.

Upon closer inspection, usage of layer_removal_cs doesn't protect all
readers, so, we will need to something about that before we get back
here.

thread 'mgmt request worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', pageserver/src/tenant/timeline.rs:2253:22
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:616:12
   1: tokio::runtime::enter::enter
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/enter.rs:40:9
   2: tokio::runtime::handle::Handle::block_on
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/handle.rs:298:34
   3: pageserver::tenant::timeline::Timeline::compact_level0
             at /home/cs/src/neon-work-2/pageserver/src/tenant/timeline.rs:2252:17
   4: pageserver::tenant::timeline::Timeline::compact
             at /home/cs/src/neon-work-2/pageserver/src/tenant/timeline.rs:575:17
   5: pageserver::tenant::timeline::Timeline::checkpoint::{{closure}}::{{closure}}
             at /home/cs/src/neon-work-2/pageserver/src/tenant/timeline.rs:505:17
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   7: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   8: pageserver::tenant::timeline::Timeline::checkpoint::{{closure}}
             at /home/cs/src/neon-work-2/pageserver/src/tenant/timeline.rs:495:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  10: pageserver::tenant::Tenant::bootstrap_timeline::{{closure}}
             at /home/cs/src/neon-work-2/pageserver/src/tenant.rs:2005:50
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  12: pageserver::tenant::Tenant::create_timeline::{{closure}}
             at /home/cs/src/neon-work-2/pageserver/src/tenant.rs:1098:73
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: pageserver::http::routes::timeline_create_handler::{{closure}}
             at /home/cs/src/neon-work-2/pageserver/src/http/routes.rs:192:221
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  18: routerify::route::Route<B,E>::process::{{closure}}
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-3.0.0/src/route/mod.rs:105:32
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  20: routerify::router::Router<B,E>::process::{{closure}}
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-3.0.0/src/router/mod.rs:308:89
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  22: <routerify::service::request_service::RequestService<B,E> as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/routerify-3.0.0/src/service/request_service.rs:56:72
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  25: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:491:35
  26: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /home/cs/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/proto/h1/dispatch.rs:297:43