Adapt test case from PR #3572
This is currently failing:

---- tenant::size::investigation_test stdout ----
calculated synthetic size: 220121784320
result: Ok("[{\"method\":\"Skipped\",\"accum_size\":220121784320},{\"method\":\"SnapshotHere\",\"accum_size\":220121784320},{\"method\":\"Wal\",\"accum_size\":67108864}]")
latest_gc_cutoff lsn 47/240A5860 is 305547335776, last_lsn lsn 47/280A5860 is 305614444640
thread 'tenant::size::investigation_test' panicked at 'assertion failed: `(left == right)`
  left: `220121784320`,
 right: `220054675456`', pageserver/src/tenant/size.rs:717:5

I believe the result this produces, `220121784320`, is correct. The expected
value (`220054675456`) doesn't include the WAL between last_lsn and
latest_gc_cutoff, but it should be included.